name: 🚀 Feature Request
description: Suggest an idea, new filter, or enhancement for Vidonex.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting new ideas to take Vidonex to the next level!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem or limitation is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution / Enhancement
      description: Describe the solution you'd like or how you envision the API/UI behavior.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions Considered
      description: Any alternative approaches or workarounds you've considered.
