// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion() {
  return window['go']['desktop']['App']['GetAppVersion']();
}

export function GetServerInfo() {
  return window['go']['desktop']['App']['GetServerInfo']();
}

export function GetSystemCapabilities() {
  return window['go']['desktop']['App']['GetSystemCapabilities']();
}

export function ImportLocalMedia(arg1, arg2) {
  return window['go']['desktop']['App']['ImportLocalMedia'](arg1, arg2);
}

export function OpenProjectFileDialog() {
  return window['go']['desktop']['App']['OpenProjectFileDialog']();
}

export function SaveProjectFileDialog(arg1) {
  return window['go']['desktop']['App']['SaveProjectFileDialog'](arg1);
}

export function SelectExportDirectory() {
  return window['go']['desktop']['App']['SelectExportDirectory']();
}

export function SelectMediaFiles() {
  return window['go']['desktop']['App']['SelectMediaFiles']();
}
