// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function GetAppVersion():Promise<string>;

export function GetServerInfo():Promise<Record<string, any>>;

export function GetSystemCapabilities():Promise<desktop.SystemCapabilities>;

export function ImportLocalMedia(arg1:string,arg2:Array<string>):Promise<Array<desktop.ImportedAssetResult>>;

export function OpenProjectFileDialog():Promise<string>;

export function SaveProjectFileDialog(arg1:string):Promise<string>;

export function SelectExportDirectory():Promise<string>;

export function SelectMediaFiles():Promise<Array<string>>;
